#!/usr/bin/env python
#
# This is a highly modified version of gl3w_gen.py.
# The original version was written by Slavomir Kaslev
# as part of gl3w which is in the public domain
# and available at https://github.com/skaslev/gl3w.
#
# Copyright (c) 2014 Daniel Kirchner
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
#
import re
import os
import urllib.request, urllib.error, urllib.parse

# Parse function names from glcorearb.h
procs = []
p = re.compile(r'GLAPI.*APIENTRY\s+(\w+)')
with open('oglp/glcorearb.h', 'r') as f:
    for line in f:
        m = p.match(line)
        if m:
            procs.append(m.group(1))

# Parse function names from glcoreext.h
for filename in ['NV_explicit_multisample.h', 'NVX_gpu_memory_info.h', 'NV_shader_buffer_load.h', 'NV_vertex_buffer_unified_memory.h']:
	with open(os.path.join('oglp/ext',filename), 'r') as f:
		for line in f:
			m = p.match (line)
			if m:
				procs.append(m.group(1))

def proc_t(proc):
    return { 'p': proc,
             'p_s': proc[2:],
             'p_t': 'PFN' + proc.upper() + 'PROC' }

# Generate glcorew.h
with open('oglp/glcorew.h', 'wt') as f:
    f.write (r'''/*
 * Copyright (c) 2014 Daniel Kirchner
 *
 * Copying and distribution of this file, with or without modification,
 * are permitted in any medium without royalty provided the copyright
 * notice and this notice are preserved.  This file is offered as-is,
 * without any warranty. 
 */
/* This file was generated by glcorew_gen.py.
 * Don't change it directly, change glcorew_gen.py instead. */
#ifndef OGLP_GLCOREW_H
#define OGLP_GLCOREW_H

#include "glcorearb.h"
#include "glcoreext.h"

namespace oglp {

typedef void *(*GetProcAddressCallback) (const char*);

void InitPrototypes (GetProcAddressCallback getprocaddress);
GLAPI int APIENTRY Unsupported (...);

''')
    for proc in procs:
        f.write('extern %(p_t)s %(p_s)s;\n' % proc_t(proc))
    f.write(r'''

} /* namespace oglp */

#endif /* !defined OGLP_GLCOREW_H */
''')

# Generate glcorew.cxx
with open('oglp/glcorew.cxx', 'wt') as f:
    f.write(r'''/*
 * Copyright (c) 2014 Daniel Kirchner
 *
 * Copying and distribution of this file, with or without modification,
 * are permitted in any medium without royalty provided the copyright
 * notice and this notice are preserved.  This file is offered as-is,
 * without any warranty. 
 */
/* This file was generated by glcorew_gen.py.
 * Don't change it directoly, change glcorew_gen.py instead.*/
#ifndef OGLP_GLCOREW_CXX
#define OGLP_GLCOREW_CXX

#include "glcorew.h"
#include <stdexcept>

namespace oglp {

''')
    for proc in procs:
        f.write('%(p_t)s %(p_s)s =\n'
		'    (%(p_t)s) Unsupported;\n' % proc_t(proc))
    f.write(r'''

GLAPI int APIENTRY Unsupported (...)
{
    throw std::runtime_error ("An unsupported OpenGL entry point was called.");
}

void InitPrototypes (GetProcAddressCallback getprocaddress)
{
    void *ptr;

''')
    for proc in procs:
        f.write('    ptr = getprocaddress ("%(p)s");\n'
		'    if (ptr) %(p_s)s = (%(p_t)s) ptr;\n'
                % proc_t(proc))
    f.write(r'''
}

} /* namespace oglp */
#endif /* !defined OGLP_GLCOREW_CXX */
''')
