if(GLM_PACKAGE_DIR)
  set(GLM_INCLUDE_DIR ${GLM_PACKAGE_DIR})
  include_directories(${GLM_INCLUDE_DIR})
else(GLM_PACKAGE_DIR)
  find_path(GLM_INCLUDE_DIR glm/glm.hpp)
endif(GLM_PACKAGE_DIR)

set(GLM_LIBRARY_DIR )


if(GLM_INCLUDE_DIR)
	set(GLM_FOUND "YES")
endif(GLM_INCLUDE_DIR)
